version: "3"
services:
  4Gift-front:
    build: ./client
    container_name: 4Gift-front
    volumes:
      - build_react:/var/www/html

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - 4Gift-front

volumes:
  build_react: