version: '3'
services:
  client_react:
    build: ./client
    container_name: client_react
    volumes:
      - build_react:/var/www/html

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - build_react:/var/www/html
    depends_on:
      - client_react

volumes:
  build_react: